@startuml

skinparam style strictuml

actor User
participant "QuickSort" as QS
activate User
User -> QS: quicksort([3, 1, 4, 1, 5])
activate QS
note top: Erster Aufruf\nListe: [3, 1, 4, 1, 5]\nPivot = 3 (erstes Element)
note right:\nPartitionierung:\nLeft = [1, 1]\nRight = [4, 5]

QS -> QS++: quicksort([1, 1])
note left: Zweiter Aufruf (für left))\nListe: [1, 1]\nPivot = 1 (erstes Element)
note right: Partitionierung:\nLeft = []\nRight = [1]
QS-->>QS
deactivate QS
note right: Kombiniere: [1] + [1] = [1, 1]

QS -> QS++: quicksort([4, 5])
note left: Dritter Aufruf (für right))\nListe: [4, 5]\nPivot = 4 (erstes Element)
note right: Partitionierung:\nLeft = []\nRight = [5]
QS-->>QS
deactivate QS
note right: Kombiniere: [] + [4] + [5] = [4, 5]

QS -->> User: return [1, 1, 3, 4, 5]
note right: Kombiniere der Aufrufe:\n[1, 1] + [3] + [4, 5] = [1, 1, 3, 4, 5]

deactivate QS
deactivate User
@enduml